version: '3.7'
services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
  redis:
    image: "redis:7-alpine"
    ports:
      - 6379
    volumes:
    - ./tmp/redis_data:/var/lib/redis/data
  rails:
    build: ./ 
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app # add our local code to dockerfile
    depends_on:
      - postgres  # add all dependant container

volumes:
  postgres: # named volume